### ISSUE TITLE
TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by eandersons** [Cyxo/adb-messaging#2]
I get the following error when starting the app on Windows 10:

>Error
>
>A JavaScript error occurred in the main process
>
>Uncaught Exception:
>TypeError: Cannot read property '0' of null
>    at getContacts (D:\adb-messaging\src\index.js:125:70)
>    at hasADB (D:\adb-messaging\src\index.js:147:3)
>    at onReady (D:\adb-messaging\src\index.js:101:3)
>    at App.createWindow (D:\adb-messaging\src\index.js:20:3)
>    at App.emit (events.js:215:7)

I tried to run the `adb` command that is right before the line that causes the error:

``` cmd
>adb shell su -c ls -l /data/data/com.android.providers.contacts/databases/contacts*.db
/system/bin/sh: su: not found
```

Without `su -c` - permission error of course:

``` cmd
>adb shell ls -l /data/data/com.android.providers.contacts/databases/contacts*.db
ls: /data/data/com.android.providers.contacts/databases/contacts*.db: Permission denied
```

Does phone must have a custom ROM and/or it must be rooted to use this application? Or am I missing something else? What are the prerequisites?

**Comment by Cyxo** [comment]
Hi! Yes the application needs the phone to be rooted for now. I think ADB can't get the messages and contacts on the phone without root permissions. In later releases I will try to get the messages without root (by installing a small app on the phone) but for now it doesn't work without root.

**Comment by eandersons** [comment]
Thank you for your response!
I am looking forward for future improvements.
